server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ostock_dev
    username: postgres
    password: 123

management:
  endpoints:
    web:
      exposure:
        include: "*"