server:
  port: 8072

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: organization-service
          uri: lb://organization-service
        - id: licensing-service
          uri: lb://licensing-service